CREATE TABLE IF NOT EXISTS authors (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT    NOT NULL,
    "desc" TEXT   NOT NULL,
    year  INTEGER NOT NULL,
    pages INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS book_authors (
    book_id__id   INTEGER NOT NULL,
    author_id__id INTEGER NOT NULL,

    PRIMARY KEY (book_id__id, author_id__id),

    FOREIGN KEY (book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (author_id__id)
        REFERENCES authors(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_genres (
    book_id__id  INTEGER NOT NULL,
    genre_id__id INTEGER NOT NULL,

    PRIMARY KEY (book_id__id, genre_id__id),

    FOREIGN KEY (book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (genre_id__id)
        REFERENCES genres(id)
        ON DELETE CASCADE
);
