-- 1) Расширение триграмм
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2) Таблицы (ваш исходный DDL)
CREATE TABLE IF NOT EXISTS authors (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  TEXT    NOT NULL,
    "desc" TEXT    NOT NULL,
    year   INTEGER NOT NULL,
    pages  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS book_authors (
    book_id__id   INTEGER NOT NULL,
    author_id__id INTEGER NOT NULL,

    PRIMARY KEY (book_id__id, author_id__id),

    FOREIGN KEY (book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (author_id__id)
        REFERENCES authors(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_genres (
    book_id__id  INTEGER NOT NULL,
    genre_id__id INTEGER NOT NULL,

    PRIMARY KEY (book_id__id, genre_id__id),

    FOREIGN KEY (book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (genre_id__id)
        REFERENCES genres(id)
        ON DELETE CASCADE
);

-- 3) Триграммные индексы под поиск (case-insensitive через lower)
-- Эти индексы поддерживают trigram-поиск и ускоряют similarity / % / LIKE / ILIKE-паттерны. :contentReference[oaicite:1]{index=1}
CREATE INDEX IF NOT EXISTS books_title_trgm_ci
    ON books USING gin (lower(title) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS authors_name_trgm_ci
    ON authors USING gin (lower(name) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS genres_name_trgm_ci
    ON genres USING gin (lower(name) gin_trgm_ops);

-- 4) Индексы под EXISTS/joins по связующим таблицам (рекомендовано)
-- PK(book_id__id, author_id__id) уже даёт индекс в порядке (book_id__id, author_id__id),
-- но для запросов, которые стартуют с author_id__id, нужен отдельный.
CREATE INDEX IF NOT EXISTS book_authors_author_id_idx
    ON book_authors (author_id__id);

CREATE INDEX IF NOT EXISTS book_genres_genre_id_idx
    ON book_genres (genre_id__id);
