CREATE TABLE IF NOT EXISTS authors (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT    NOT NULL,
    "desc" TEXT   NOT NULL,
    year  INTEGER NOT NULL,
    pages INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS book_authors (
    ba_book_id__id   INTEGER NOT NULL,
    ba_author_id__id INTEGER NOT NULL,

    PRIMARY KEY (ba_book_id__id, ba_author_id__id),

    FOREIGN KEY (ba_book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (ba_author_id__id)
        REFERENCES authors(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_genres (
    bg_book_id__id  INTEGER NOT NULL,
    bg_genre_id__id INTEGER NOT NULL,

    PRIMARY KEY (bg_book_id__id, bg_genre_id__id),

    FOREIGN KEY (bg_book_id__id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    FOREIGN KEY (bg_genre_id__id)
        REFERENCES genres(id)
        ON DELETE CASCADE
);
